
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: compound_backend
    networks:
      - test-new
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=jwtsecret
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=compound_db
      - DB_USER=root
      - DB_PORT=3306
  db:
    image: mysql:8.0
    container_name: compound_mysql
    networks:
      - test-new
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: compound_db
    ports:
      - "3306:3306"
    volumes:
      - test-new:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
  adminer:
    image: adminer
    networks:
      - test-new
    ports:
      - "8080:8080"

volumes:
  test-new:
    name: test-new
    external: true
networks:
  test-new:
    external: true